chore: remove unused copybara_options from GitHub Actions workflow
ERROR: --init-history is not compatible with CHANGE_REQUEST
Signed-off-by: Luong Vo <vo.tran.thanh.luong@gmail.com>
GitOrigin-RevId: 4edd0e2ff350f3095cf24fd20c6b3d1c2dad0274